In [2]:
from pathlib import Path
import pandas as pd

# Run this script while within this project at the root folder
ROOT_PATH = Path.cwd().resolve().parent
FOLDER = 'data'
SUB_FOLDER = 'raw'
YEAR = '2025'
FILE_NAME = 'yellow_tripdata_2025-01.parquet'
raw_data = pd.read_parquet(ROOT_PATH / FOLDER / SUB_FOLDER / YEAR /  FILE_NAME)

# Display options
pd.options.display.max_columns = None
pd.options.display.float_format = '{:.4f}'.format

## Viewing data

In [3]:
print(raw_data.info())

<class 'pandas.DataFrame'>
RangeIndex: 3475226 entries, 0 to 3475225
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 493.5 MB
None

In [4]:
display(raw_data.describe())

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,3475226.0000,3475226,3475226,2935077.0000,3475226.0000,2935077.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,3475226.0000,2935077.0000,2935077.0000,3475226.0000
mean,1.7854,2025-01-17 11:02:55.910964,2025-01-17 11:17:56.997901,1.2979,5.8551,2.4825,165.1916,164.1252,1.0366,17.0818,1.3177,0.4781,2.9598,0.4493,0.9548,25.6113,2.2252,0.1239,0.4834
min,1.0000,2024-12-31 20:47:55,2024-12-18 07:52:40,0.0000,0.0000,1.0000,1.0000,1.0000,0.0000,-900.0000,-7.5000,-0.5000,-86.0000,-126.9400,-1.0000,-901.0000,-2.5000,-1.7500,-0.7500
25%,2.0000,2025-01-10 07:59:01,2025-01-10 08:15:29.500000,1.0000,0.9800,1.0000,132.0000,113.0000,1.0000,8.6000,0.0000,0.5000,0.0000,0.0000,1.0000,15.2000,2.5000,0.0000,0.0000
50%,2.0000,2025-01-17 15:41:33,2025-01-17 15:59:34,1.0000,1.6700,1.0000,162.0000,162.0000,1.0000,12.1100,0.0000,0.5000,2.4500,0.0000,1.0000,19.9500,2.5000,0.0000,0.7500
75%,2.0000,2025-01-24 19:34:06,2025-01-24 19:48:31,1.0000,3.1000,1.0000,234.0000,234.0000,1.0000,19.5000,2.5000,0.5000,3.9300,0.0000,1.0000,27.7800,2.5000,0.0000,0.7500
max,7.0000,2025-02-01 00:00:44,2025-02-01 23:44:11,9.0000,276423.5700,99.0000,265.0000,265.0000,5.0000,863372.1200,15.0000,10.5000,400.0000,170.9400,1.0000,863380.3700,2.5000,6.7500,0.7500
std,0.4263,NaN,NaN,0.7508,564.6016,11.6328,64.5295,69.4017,0.7013,463.4729,1.8615,0.1375,3.7797,2.0026,0.2782,463.6585,0.9040,0.4725,0.3619

In [5]:
display(raw_data.head(5))

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0000,1.6000,1.0000,N,229,237,1,10.0000,3.5000,0.5000,3.0000,0.0000,1.0000,18.0000,2.5000,0.0000,0.0000
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0000,0.5000,1.0000,N,236,237,1,5.1000,3.5000,0.5000,2.0200,0.0000,1.0000,12.1200,2.5000,0.0000,0.0000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0000,0.6000,1.0000,N,141,141,1,5.1000,3.5000,0.5000,2.0000,0.0000,1.0000,12.1000,2.5000,0.0000,0.0000
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0000,0.5200,1.0000,N,244,244,2,7.2000,1.0000,0.5000,0.0000,0.0000,1.0000,9.7000,0.0000,0.0000,0.0000
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0000,0.6600,1.0000,N,244,116,2,5.8000,1.0000,0.5000,0.0000,0.0000,1.0000,8.3000,0.0000,0.0000,0.0000

## Clean Data

In [7]:
# Apply filter to remove dirty data
cleaned_data = raw_data[
    (raw_data["trip_distance"] > 0.0)
    & (raw_data["fare_amount"] > 0.0)
    & (raw_data["passenger_count"] > 0.0)
    & (raw_data["trip_distance"].notna())
    & (raw_data["fare_amount"].notna())
    & (raw_data["passenger_count"].notna())
    & (raw_data["tpep_dropoff_datetime"] > raw_data["tpep_pickup_datetime"])
]
display(cleaned_data.head(5))
print(cleaned_data.info())

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0000,1.6000,1.0000,N,229,237,1,10.0000,3.5000,0.5000,3.0000,0.0000,1.0000,18.0000,2.5000,0.0000,0.0000
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0000,0.5000,1.0000,N,236,237,1,5.1000,3.5000,0.5000,2.0200,0.0000,1.0000,12.1200,2.5000,0.0000,0.0000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0000,0.6000,1.0000,N,141,141,1,5.1000,3.5000,0.5000,2.0000,0.0000,1.0000,12.1000,2.5000,0.0000,0.0000
3,2,2025-01-01 00:14:27,2025-01-01 00:20:01,3.0000,0.5200,1.0000,N,244,244,2,7.2000,1.0000,0.5000,0.0000,0.0000,1.0000,9.7000,0.0000,0.0000,0.0000
4,2,2025-01-01 00:21:34,2025-01-01 00:25:06,3.0000,0.6600,1.0000,N,244,116,2,5.8000,1.0000,0.5000,0.0000,0.0000,1.0000,8.3000,0.0000,0.0000,0.0000

<class 'pandas.DataFrame'>
Index: 2815614 entries, 0 to 2935076
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 421.9 MB
None

## Validate Cleaned Data

In [8]:
# Possible inconsistency in how total_amount column is derived
validation_data = cleaned_data.copy()
validation_data["computed_total_amount"] = (
    cleaned_data["fare_amount"] + cleaned_data["extra"] + cleaned_data["mta_tax"]
    + cleaned_data["tip_amount"] + cleaned_data["tolls_amount"] + cleaned_data["improvement_surcharge"]
    + cleaned_data["congestion_surcharge"] + cleaned_data["Airport_fee"] +  cleaned_data["cbd_congestion_fee"]
)
validation_data["difference"] = validation_data["computed_total_amount"] - validation_data["total_amount"]
validation_data[validation_data["computed_total_amount"] != validation_data["total_amount"]].head(5)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee,computed_total_amount,difference
0,1,2025-01-01 00:18:38,2025-01-01 00:26:59,1.0000,1.6000,1.0000,N,229,237,1,10.0000,3.5000,0.5000,3.0000,0.0000,1.0000,18.0000,2.5000,0.0000,0.0000,20.5000,2.5000
1,1,2025-01-01 00:32:40,2025-01-01 00:35:13,1.0000,0.5000,1.0000,N,236,237,1,5.1000,3.5000,0.5000,2.0200,0.0000,1.0000,12.1200,2.5000,0.0000,0.0000,14.6200,2.5000
2,1,2025-01-01 00:44:04,2025-01-01 00:46:01,1.0000,0.6000,1.0000,N,141,141,1,5.1000,3.5000,0.5000,2.0000,0.0000,1.0000,12.1000,2.5000,0.0000,0.0000,14.6000,2.5000
13,1,2025-01-01 00:30:07,2025-01-01 00:36:48,1.0000,1.1000,1.0000,N,229,141,2,7.9000,3.5000,0.5000,0.0000,0.0000,1.0000,12.9000,2.5000,0.0000,0.0000,15.4000,2.5000
14,1,2025-01-01 00:39:55,2025-01-01 01:13:59,1.0000,3.2000,1.0000,N,141,113,1,26.1000,3.5000,0.5000,7.8000,0.0000,1.0000,38.9000,2.5000,0.0000,0.0000,41.4000,2.5000

## Create dataset with only computed total amount, replace datetime columns with date and hour columns

In [9]:
computed_data = cleaned_data.copy()
computed_data["computed_total_amount"] = (
    cleaned_data["fare_amount"] + cleaned_data["extra"] + cleaned_data["mta_tax"]
    + cleaned_data["tip_amount"] + cleaned_data["tolls_amount"] + cleaned_data["improvement_surcharge"]
    + cleaned_data["congestion_surcharge"] + cleaned_data["Airport_fee"] +  cleaned_data["cbd_congestion_fee"]
)
computed_data["pickup_date"] = computed_data["tpep_pickup_datetime"].dt.date
computed_data["pickup_hour"] = computed_data["tpep_pickup_datetime"].dt.hour
computed_data["dropoff_date"] = computed_data["tpep_dropoff_datetime"].dt.date
computed_data["dropoff_hour"] = computed_data["tpep_dropoff_datetime"].dt.hour
computed_data = computed_data.drop(columns = (['tpep_pickup_datetime','tpep_pickup_datetime','tpep_dropoff_datetime','tpep_dropoff_datetime',
    'fare_amount','extra','mta_tax','tip_amount','tolls_amount','improvement_surcharge','total_amount','congestion_surcharge','Airport_fee','cbd_congestion_fee']))
# computed_data.columns
column_order = [
    'VendorID',
    'PULocationID',
    'pickup_date',
    'pickup_hour',
    'DOLocationID',
    'dropoff_date',
    'dropoff_hour',
    'passenger_count',
    'trip_distance',
    'RatecodeID',
    'store_and_fwd_flag',
    'payment_type',
    'computed_total_amount'
    ]
computed_data = computed_data[column_order]
computed_data

,VendorID,PULocationID,pickup_date,pickup_hour,DOLocationID,dropoff_date,dropoff_hour,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,payment_type,computed_total_amount
0,1,229,2025-01-01,0,237,2025-01-01,0,1.0000,1.6000,1.0000,N,1,20.5000
1,1,236,2025-01-01,0,237,2025-01-01,0,1.0000,0.5000,1.0000,N,1,14.6200
2,1,141,2025-01-01,0,141,2025-01-01,0,1.0000,0.6000,1.0000,N,1,14.6000
3,2,244,2025-01-01,0,244,2025-01-01,0,3.0000,0.5200,1.0000,N,2,9.7000
4,2,244,2025-01-01,0,116,2025-01-01,0,3.0000,0.6600,1.0000,N,2,8.3000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2935072,1,163,2025-01-31,23,48,2025-01-31,23,1.0000,1.5000,1.0000,N,2,17.6000
2935073,1,48,2025-01-31,23,48,2025-01-31,23,1.0000,0.6000,1.0000,N,2,14.1000
2935074,2,142,2025-01-31,23,164,2025-01-31,23,1.0000,1.9600,1.0000,N,1,21.9500
2935075,2,230,2025-01-31,23,142,2025-01-31,23,2.0000,0.8900,1.0000,N,1,15.5400
2935076,2,140,2025-01-31,23,75,2025-01-31,23,2.0000,2.4400,1.0000,N,1,24.0000